name: 'mpatel-maven-webgoat'
on:
  push:
    branches:
      - "**"
  pull_request:
    types: 
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
  security-events: write # Required for uploading code scanning.

env:
  RT_REPO_MVN_RELEASE: "rsa-demo-maven-release"
  RT_REPO_MVN_SNAPSHOT: "rsa-demo-maven-sanpshot"
  RT_REPO_DOCKER_LOCAL: "rsa-demo-docker-local"

jobs:
 mvn-build-and-publish:
   runs-on: ubuntu-latest
   env:
     BUILD_NAME: 'maven-webgoat'
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
        java-version: '17'
        distribution: 'temurin'
     - name: Setup JFrog CLI
       uses: jfrog/setup-jfrog-cli@v4
       id: setup-cli
       env:
        JF_URL: ${{ secrets.JF_URL }}
       with:
        oidc-provider-name: omriz-oidc
        oidc-token-audience: omriz-oidc
     - name: Login to JFrog Artifactory (Docker)
       env:
         JF_URL: ${{ secrets.JF_URL }}
         JF_ARTIFACTORY_USER: omriz
         JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
       run: |
         JF_HOST="${JF_URL#https://}"
         echo "JF_HOST=${JF_HOST}" >> $GITHUB_ENV
         echo "$JF_ACCESS_TOKEN" | docker login "$JF_HOST" -u "$JF_ARTIFACTORY_USER" --password-stdin
     - name: Health check JFrog Artifactory instance 🐸
       run: |
        jf --version
        jf rt ping
        jf mvnc --repo-resolve-releases "${{ env.RT_REPO_MVN_RELEASE }}" --repo-resolve-snapshots "${{ env.RT_REPO_MVN_SNAPSHOT }}" --repo-deploy-releases "${{ env.RT_REPO_MVN_RELEASE }}" --repo-deploy-snapshots "${{ env.RT_REPO_MVN_SNAPSHOT }}"
     - name: Fix Code Formatting with Spotless
       run: mvn spotless:apply
     - name: Curation Audit
       run: |
        jf ca --format=table --threads=100
     - name: Build Maven Package
       run: |
        jf mvn clean install -f pom.xml -Dmaven.test.skip=true -Dartifactory.publish.artifacts=true --build-name ${{env.BUILD_NAME}} --build-number ${{github.run_number}}
     - name: Security Audit
       run: |
        jf audit
     - name: Docker Build 🐳🐸 and scan
       run: |
         jf docker build . -t $JF_HOST/${{ env.RT_REPO_DOCKER_LOCAL }}/maven-webgoat:${{ github.run_number }}
         jf docker scan $JF_HOST/${{ env.RT_REPO_DOCKER_LOCAL }}/maven-webgoat:${{ github.run_number }}
         jf docker push $JF_HOST/${{ env.RT_REPO_DOCKER_LOCAL }}/maven-webgoat:${{ github.run_number }}
     - name: Publish build build-info
       run: |
         # Collect and store environment variables in the build-info
         jf rt bce ${{env.BUILD_NAME}} ${{github.run_number}}
         # Collect and store VCS details in the build-info
         jf rt bag ${{env.BUILD_NAME}} ${{github.run_number}}
         # Publish the build-info to Artifactory
         jf rt bp ${{env.BUILD_NAME}} ${{github.run_number}}
         # Scan the published build-info with Xray
         jf rt bs ${{env.BUILD_NAME}} ${{github.run_number}}
